spring:
  application:
    name: az-smb-integration

smb:
  host: 192.168.0.10        # IP or hostname of SMB server
  port: 445                 # Port of SMB server
  share: SharedFolder       # Name of the SMB shared folder
  domain: "migration"       # Optional, keep blank for workgroup
  username: myuser
  password: mypassword

